config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :show]
  get 'profile', to: 'users#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
  resources :likes
  resources :follows
  resources :posts do
    resources :comments
  end
  resources :pages, :path => "about", only: [:index]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, length: {maximum: 500}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    current_user.comments << @comment

    respond_to do |format|
      if @comment.save
        # redirect_to posts_path
        format.turbo_stream
      else
        # render :new, status: :unprocessable_entity
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update(comment_params)
        # redirect_to posts_path
        format.turbo_stream
      else
        # render :edit, status: :unprocessable_entity
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to posts_path
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= tag.div id: dom_id(Comment.find(comment.id)) do %>
  <%= turbo_frame_tag "edit_comment" do %>
    <div class="comment-container">
      <div class="comment-header">
        <div class="user">
          <% user = User.find(comment.user_id) %>
          <div>
            <% if user.avatar.attached? %>
              <%= image_tag user.avatar %>
            <% elsif user.image.nil? %>
              <%= image_tag "default-profile-icon.jpeg" %>
            <% else %>
              <%= image_tag "#{user.image}" %>
            <% end %>
          </div>
          <div class="comment-user">
            <% if user == current_user %>
              <%= link_to "#{user.username}", profile_path, data: { turbo_frame: "_top" } %>
            <% else %>
              <%= link_to "#{user.username}", user_path(user.id), data: { turbo_frame: "_top" } %>
            <% end %>
          </div>
        </div>
        <div class="comment-menu">
          <% if comment.user_id == current_user.id %>
            <div>
              <%= link_to "Edit", edit_post_comment_path(comment.post_id, comment.id) %>
            </div>
            <div>
              <%= button_to "", post_comment_path(comment.post_id, comment.id), method: :delete, data: { turbo_frame: "_top" }, class: "delete" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="comment-content">
        <%= comment.content %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/comments/_comment_form.html.erb
<%= form_with model: @comment, url: comments_path(post_id: post_id) do |f| %>
  <%= f.text_area :content, placeholder:"Write a comment..." %><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.append dom_id(Post.find(@comment.post_id), :comments), @comment %>
<%= turbo_stream.update dom_id(Post.find(@comment.post.id), :add_comment) do %>
  <%= turbo_frame_tag "add_comment" do %>
    <%= button_to "Add Comment", new_post_comment_path(@post.id), method: :get %>
  <% end %>
<% end %>
<%= turbo_stream.update dom_id(Post.find(@post.id), :comment_count) do %>
  <% if @post.comments.count == 1 %>
    <%= "#{@post.comments.count} Comment"%>
  <% else %>
    <%= "#{@post.comments.count} Comments"%>
  <% end %>
<% end %>

app/views/comments/edit.html.erb
<%= turbo_frame_tag "edit_comment" do %>
  <%= form_with model: [ @post, @comment ], url: [ @post, @comment ] do |f| %>
    <%= f.text_area :content, placeholder: @comment.content %><br>
    <%= f.submit "Submit", class: "submit" %>
  <% end %>
<% end %>

app/views/comments/new.html.erb
<%= turbo_frame_tag "add_comment" do %>
  <%= form_with model: [ @post, @comment ], url: [ @post, @comment ] do |f| %>
    <% if @comment.errors.any? %>
      <ul class="errors">
        <% @comment.errors.full_messages.each do |message| %>
          <li class="error-message"><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    <%= f.text_area :content, placeholder:"Write a comment..." %><br>
    <%= f.submit "Submit", class: "submit" %>
  <% end %>
<% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.update dom_id(Comment.find(@comment.id)) do %>
  <%= turbo_frame_tag "edit_comment" do %>
    <div class="comment-container">
      <div class="comment-header">
        <div class="user">
          <% user = User.find(@comment.user_id) %>
          <div>
            <%= image_tag "#{user.image}" %>
          </div>
          <div class="comment-user">
            <%= user.username %>
          </div>
        </div>
        <div class="comment-menu">
          <% if @comment.user_id == current_user.id %>
            <div>
              <%= link_to "Edit", edit_post_comment_path(@comment.post_id, @comment.id) %>
            </div>
            <div>
              <%= button_to "", post_comment_path(@comment.post_id, @comment.id), method: :delete, data: { turbo_frame: "_top" }, class: "delete" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="comment-content">
        <%= @comment.content %>
      </div>
    </div>
  <% end %>
<% end %>