config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :show]
  get 'profile', to: 'users#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
  resources :likes
  resources :follows
  resources :posts do
    resources :comments
  end
  resources :pages, :path => "about", only: [:index]
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, foreign_key: "follower_id", class_name: "User"
  belongs_to :followee, foreign_key: "followee_id", class_name: "User"
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def index
    p params
    @user = params[:user_id]
    @follows = Follow.where(followee_id: params[:user_id]).or(Follow.where(follower_id: params[:user_id]))
  end

  def new
    @follow = Follow.new
  end

  def create
    @follow = Follow.new(follow_params)

    if @follow.save
      redirect_to request.referrer
    else
      redirect_to request.referrer, status: :unprocessable_entity
    end
  end

  def destroy
    @follow = Follow.find(params[:id])
    @follow.destroy
    redirect_to request.referrer
  end

  private

  def follow_params
    params.require(:follow).permit(:follower_id, :followee_id)
  end
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/views/follows/_follow.html.erb
<div>
  <% if user != current_user %>
    <% follow = current_user.followee_follows.find_by(followee_id: user.id) %>
    <% if follow.nil? %>
      <%= button_to "Follow", follows_path({"follow"=>{followee_id: user.id, follower_id: current_user}}) %>
    <% else %>
      <%= button_to "Unfollow", follow_path(follow), method: :delete %>
    <% end %>
  <% end %>
</div>

app/views/follows/_follow_button.html.erb
<div>
  <% if user != current_user %>
    <% follow = current_user.followee_follows.find_by(followee_id: user.id) %>
    <% if follow.nil? %>
      <%= button_to "Follow", follows_path({"follow"=>{followee_id: user.id, follower_id: current_user}}) %>
    <% else %>
      <%= button_to "Unfollow", follow_path(follow), method: :delete %>
    <% end %>
  <% end %>
</div>

app/views/follows/index.html.erb
<div class="page-container">
  <div class="follow-data" data-controller="toggle" data-toggle-hide-class="hide" data-toggle-primary-class="select">
    <div class="follow-buttons">
      <button data-action="click->toggle#follower" data-toggle-target="button">Followers</button>
      <button data-action="click->toggle#following" data-toggle-target="button">Following</button>
    </div>
    <div class="followers" data-toggle-target="follower">
      <% @follows.where(followee_id: @user).each do |follow| %>
        <% user = User.find(follow.follower_id) %>
        <div class="user-show-display">
          <div class="user-info-index">
            <div>
              <% if user.image.nil? %>
                <%= image_tag "default-profile-icon.jpeg" %>
              <% else %>
                <%= image_tag "#{user.image}" %>
              <% end %>
            </div>
            <div class="username-index">
              <%= link_to "#{user.username}", user_path(user.id) %>
            </div>
          </div>
          <div class="follow">
            <%= render "follows/follow_button", user: user %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="following" data-toggle-target="following">
      <% @follows.where(follower_id: @user).each do |follow| %>
        <% user = User.find(follow.followee_id) %>
        <div class="user-show-display">
          <div class="user-info-index">
            <div>
              <% if user.image.nil? %>
                <%= image_tag "default-profile-icon.jpeg" %>
              <% else %>
                <%= image_tag "#{user.image}" %>
              <% end %>
            </div>
            <div class="username-index">
              <%= link_to "#{user.username}", user_path(user.id) %>
            </div>
          </div>
          <div class="follow">
            <%= render "follows/follow_button", user: user %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>