config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations'
  }
  resources :users, only: [:index, :show]
  get 'profile', to: 'users#show'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
  resources :likes
  resources :follows
  resources :posts do
    resources :comments
  end
  resources :pages, :path => "about", only: [:index]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image

  validates :content, length: {maximum: 500}

  validate :image_or_content?

  validate :acceptable_image

  def acceptable_image
    return unless image.attached?

    unless image.blob.byte_size <= 1.megabyte
      errors.add(:image, "must be less than 1 MB.")
    end

    acceptable_types = ["image/jpeg", "image/png", "image/jpg"]
    unless acceptable_types.include?(image.content_type)
      errors.add(:image, "must be a JPG or PNG.")
    end
  end

  def image_or_content?
    return unless content.empty? && !image.attached?

    errors.add(:post, "must contain text or an image.")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @followees = []
    current_user.followees.each do |followee|
      @followees << followee.id
    end
    @posts = Post.where(user_id: current_user).or(Post.where(user_id: @followees)).order(id: :desc)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        # redirect_to posts_path(@post.id)
        format.turbo_stream
      else
        # render :new, status: :unprocessable_entity
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update(post_params)
        # redirect_to posts_path(@post.id)
        format.turbo_stream
      else
        # render :new, status: :unprocessable_entity
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to request.referrer
  end

  private

  def post_params
    params.require(:post).permit(:content, :image)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="post-container">
  <%= tag.div id: dom_id(Post.find(post.id), :edit) do %>
    <%= turbo_frame_tag "edit_post" do %>
      <div class="post-header">
        <div class="user">
          <div>
            <% if post.user.avatar.attached? %>
              <%= image_tag post.user.avatar %>
            <% elsif post.user.image.nil? %>
              <%= image_tag "default-profile-icon.jpeg" %>
            <% else %>
              <%= image_tag "#{post.user.image}" %>
            <% end %>
          </div>
          <div class="post-user">
            <% if post.user == current_user %>
              <%= link_to "#{post.user.username}", profile_path, data: { turbo_frame: "_top" } %>
            <% else %>
              <%= link_to "#{post.user.username}", user_path(post.user.id), data: { turbo_frame: "_top" } %>
            <% end %>
          </div>
        </div>
        <div class="post-menu">
          <% if post.user_id == current_user.id %>
            <div>
              <%= link_to "Edit", edit_post_path(post.id), method: :get %>
            </div>
            <div>
              <%= button_to "", post_path(post.id), method: :delete, data: { turbo_frame: "_top" }, class: "delete" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="content">
        <div class="content-text">
          <%= post.content %>
        </div>
        <div>
          <% if post.image.attached? %>
            <%= image_tag post.image %>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="like-comment-count">
    <div class="likes">
      <div class="like-count">
        <%= post.likes.count %>
      </div>
      <div class="like-button">
        <%= render "likes/like", post_id: post.id, post: post %>
      </div>
    </div>
    <%= tag.div id: dom_id(Post.find(post.id), :comment_count) do %>
      <% if post.comments.count == 1 %>
        <%= "#{post.comments.count} Comment"%>
      <% else %>
        <%= "#{post.comments.count} Comments"%>
      <% end %>
    <% end %>
  </div>
  <%= tag.div id: dom_id(Post.find(post.id), :comments) do %>
    <% post.comments.order(id: :asc).each do |comment| %>
      <%= render "comments/comment", comment: comment %>
    <% end %>
  <% end %>
  <%= tag.div id: dom_id(Post.find(post.id), :add_comment) do %>
    <%= turbo_frame_tag "add_comment" do %>
      <%= button_to "Add Comment", new_post_comment_path(post.id), method: :get %>
    <% end %>
  <% end %>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts", @post %>
<%= turbo_stream.update "new-post" do %>
  <%= turbo_frame_tag "new_post" do %>
    <%= button_to "New Post", new_post_path, method: :get %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<%= turbo_frame_tag "edit_post" do %>
  <%= form_with model: @post do |f| %>
    <div class="post-form">
      <div class="field">
        <%= f.text_area :content, placeholder: "What would you like to share?" %>
      </div>
      <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
      <div class="field">
        <%= f.submit "Submit", class: "submit" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/posts/index.html.erb
<div class="page-container">
  <div id="new-post" class="new-post">
    <%= turbo_frame_tag "new_post" do %>
      <%= button_to "New Post", new_post_path, method: :get %>
    <% end %>
  </div>
  <div id="posts">
    <%= render @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<%= turbo_frame_tag "new_post" do %>
  <%= form_with model: @post do |f| %>
    <div class="post-form">
      <% if @post.errors.any? %>
        <ul class="errors">
          <% @post.errors.full_messages.each do |message| %>
            <li class="error-message"><%= message %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="field">
        <%= f.text_area :content, placeholder: "What would you like to share?" %>
      </div>
      <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
      <div class="field">
        <%= f.submit "Submit", class: "submit" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<%= @post.content %>
<%= @post.user_id %>

app/views/posts/update.turbo_stream.erb
<%= turbo_stream.update dom_id(Post.find(@post.id), :edit) do %>
  <%= turbo_frame_tag "edit_post" do %>
    <div class="post-header">
        <div class="user">
          <div>
            <% if @post.user.image.nil? %>
              <%= image_tag "default-profile-icon.jpeg" %>
            <% else %>
              <%= image_tag "#{@post.user.image}" %>
            <% end %>
          </div>
          <div class="post-user">
            <%= @post.user.username %><br>
          </div>
        </div>
        <div class="post-menu">
          <% if @post.user_id == current_user.id %>
            <div>
              <%= link_to "Edit", edit_post_path(@post.id), method: :get %>
            </div>
            <div>
              <%= button_to "", post_path(@post.id), method: :delete, class: "delete" %>
            </div>
          <% end %>
        </div>
      </div>
      <div class="content">
        <div class="content-text">
          <%= @post.content %>
        </div>
        <div>
          <% if @post.image.attached? %>
            <%= image_tag @post.image %>
          <% end %>
        </div>
      </div>
  <% end %>
<% end %>